spring:
  config:
    import: 'aws-parameterstore:'
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    aws:
      parameterstore:
        enabled: true
        prefix: /server
        name: cloud-parameter-store
        profileSeparator: "_"


jwt:
  secret_key: ${JWT_SECRET_KEY}
